language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- sudo curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname
  -s`-`uname -m` -o /usr/local/bin/docker-compose
- sudo chmod +x /usr/local/bin/docker-compose
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn clean
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=./target/backend.jar -t $DOCKER_USERNAME/se234-lab10-backend  .
- docker push  $DOCKER_USERNAME/se234-lab10-backend
- docker pull  $DOCKER_USERNAME/se234-lab10-client
script:
- docker-compose -H $DOCKER_HOST up -d
after_success:
- docker ps
env:
  global:
  - secure: qnM0LMg80zMHRS84hE5/94O7Un1v8xotyAFMRrMbkEKKv2ZJPIB1MWc/z8c9LZYVibfigaHQvL7fz4L7a/1KeZl2BNrCT1i8iSRnurvtwf9W8kZBahrFRoGfTrfAL5an0N8Fop4/N9Ac1pfSEqSqErGs+70pCvOLCazxq/rvFcoOVsVm6QnSVcTEEGf67Ao1FGCbVGZtQLd7iSItKdRj0YzVQXWJ+ypoEdx6o5oXaifTBV+OtULzERmHYajq4UVusyxiwoiQ3YxFqoYprCw7dKCfBf5aCqZwSiTzkCkqG/vtArltX7ChQ/KJ109WFU2nxxmwn7CCvdyEAAkaMPQVYImA6okK/NeVehnr312WK2dMVHaEmtegLvXlAuIfZadUWbXUb0LqDQYBMhc/Qcj0zzdVoXUl1QINTyskM6KW9OqW1UvNbdM7lP0+5kk8uxrxk1K+XDU2zXeUYVXCCR9kgfdbUqd6ncby9JzjHWA+D6slomHrRt+WD+Xu4NPZY97JIIhTy3aTnFNHY2CZ2Ws3CYC6s1jxLMcGyZj1prCCY8yYzpDMKmzE533lFWVKonzhidracMgXZ3pFOmnlA7EVuiQ+ivsI5xGUodmVBCa7t0M9A5YSV6T7oTNgwGxmYz5pM/xY9eL2QZsUz+PRBy1mqcQmyvi7tTuvgm6fLtE3kIM=
  - secure: aKeD7zdnSJnAVXBEWGCmsJikEJOa5L/FLOFk5WS0GauXh83HCNV8/DlM78qfe3HFT2zpguRk2rp39TkJSpZexHPSTSp6NklkrNnpDyLQGGwhN1sPY/ow6CVARUoWsS3R9DR4CJgn1GLoqG+609yUHb8IwdY/ZI0cw12fZb6JakR4K/EELvXJ8/EMF9hgEuAM0IMjbDi8I+zXACN4xfU0J+MXwYYD7JPWb286wGvcqm8+R5eMTn+JFAB2GcRGmtrNS1tl5hqxQp0ipPOaLk1B7bYhK9vj7AWj1WikyxHnEvgnllov+l4fxWdwAWJRGg7lKfZ0vwKREqmPo7gLruLbkpSicjMs070cJtWzMk3wly8o0MiDj/JqHefc5G418XQurDtembfGxnld/0/mEZxrvKpTkv+HkT6M2J8YSINw0EldXY0r9ZWIIZg09CFqs511dnEDLXIgXPPS3iPUEdK9Gw4ti2PkB3Nv6IEHPejzQKGLX/9DYtse6eapFHt/TqE+vM4pTt20GzWGccQVTQslmo4uJml+ghQqaBdeV0i0eJyLVgZ5rEtPWUxIo6V/5QhIZOxCjEcxq8QBnSmBMRCaP/8sm57UyaHy87Gr2y0nrPGX2hvd2Zv93w/hW1KKx053bH4ooI0oGNNlZqCaj+2XB4vFQC0wq/hS9C6dv1wOa4Q=